In [1]:
import pandas as pd
import numpy as np

In [2]:
# Access a Group of Rows and Column in Pandas.
# first of all create Dataframe

# dataframe.loc

In [3]:
# DateType in pandas 


data = { 
         'students': ["john", "ram", "shyam","shivam","shubham"],
          'Rank'    :[1,2,3,4,5],
          'Marks'   :[98,87,77,69,90]

}

In [4]:
# create dataframe using the dataframe() method with index
data = { 
         'students': ["john", "ram", "shyam","shivam","shubham"],
          'Rank'    :[1,2,3,4,5],
          'Marks'   :[98,87,77,69,90]

}


df = pd.DataFrame(data, index=['RowA','ROwB','RowC','RowD','RowE'])
print("Student Records\n\n", df)
print("\n Dataframe:\n", df)

Student Records

      students  Rank  Marks
RowA     john     1     98
ROwB      ram     2     87
RowC    shyam     3     77
RowD   shivam     4     69
RowE  shubham     5     90

 Dataframe:
      students  Rank  Marks
RowA     john     1     98
ROwB      ram     2     87
RowC    shyam     3     77
RowD   shivam     4     69
RowE  shubham     5     90

In [5]:
# pandas.Dataframe. ndim

data = { 
         'students': ["john", "ram", "shyam","shivam","shubham"],
          'Rank'    :[1,2,3,4,5],
          'Marks'   :[98,87,77,69,90]

}
df = pd.DataFrame(data, index=['RowA','RowB','RowC','RowD','RowE'])
df

     students  Rank  Marks
RowA     john     1     98
RowB      ram     2     87
RowC    shyam     3     77
RowD   shivam     4     69
RowE  shubham     5     90

In [6]:
# pandas .dataframe.size.attributes

data = { 
         'students': ["john", "ram", "shyam","shivam","shubham"],
          'Rank'    :[1,2,3,4,5],
          'Marks'   :[98,87,77,69,90]
}
df = pd.DataFrame(data, index=['RowA','RowB','RowC','RowD','RowE'])
df.size

15

In [7]:
# Shape Attributes in pandas
data = { 
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
          'Rank'    :[1,2,3,4,5,6],
          'Marks'   :[98,87,77,69,90,88]
}
df = pd.DataFrame(data, index=['RowA','RowB','RowC','RowD','RowE','RowF'])
df

print(df.shape)
print(df.index)
print(df.T)
print(df.head)
print(df.tail)

(6, 3)
Index(['RowA', 'RowB', 'RowC', 'RowD', 'RowE', 'RowF'], dtype='str')
          RowA RowB   RowC    RowD     RowE   RowF
students  john  ram  shyam  shivam  shubham  rishi
Rank         1    2      3       4        5      6
Marks       98   87     77      69       90     88
<bound method NDFrame.head of      students  Rank  Marks
RowA     john     1     98
RowB      ram     2     87
RowC    shyam     3     77
RowD   shivam     4     69
RowE  shubham     5     90
RowF    rishi     6     88>
<bound method NDFrame.tail of      students  Rank  Marks
RowA     john     1     98
RowB      ram     2     87
RowC    shyam     3     77
RowD   shivam     4     69
RowE  shubham     5     90
RowF    rishi     6     88>

In [8]:
# joins in dataframe pandas 

dataset1 = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
          'Rank'    :[1,2,3,4,5,6]
         
        
         
}
dataset2 = {  
          'Roll No' :[1,4,7,5,7,9],
          'Marks'   :[98,87,77,69,90,85]

}


dataset1 = pd.DataFrame(dataset1)
print(dataset1)

dataset2 = pd.DataFrame(dataset2)
print(dataset2)

joinDF = dataset1.join(dataset2)
print(joinDF)

    ID students  Rank
0  S01     john     1
1  S02      ram     2
2  S03    shyam     3
3  S04   shivam     4
4  S05  shubham     5
5  S06    rishi     6
   Roll No  Marks
0        1     98
1        4     87
2        7     77
3        5     69
4        7     90
5        9     85
    ID students  Rank  Roll No  Marks
0  S01     john     1        1     98
1  S02      ram     2        4     87
2  S03    shyam     3        7     77
3  S04   shivam     4        5     69
4  S05  shubham     5        7     90
5  S06    rishi     6        9     85

In [7]:
# concatenate pandas dataframe


dataset1 = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
          'Rank'    :[1,2,3,4,5,6]

         
}

dataset2 = {  
          'Roll No' :[1,4,7,5,7,9],
          'Marks'   :[98,87,77,69,90,85]

}

dataset1 = pd.DataFrame(dataset1, index=['student1','student2','student3','student4','student5','student6'])
print(dataset1)
dataset2 = pd.DataFrame(dataset2, index=['student1','student2','student3','student4','student5','student6'])

resultDF = pd.concat([dataset1,dataset2])
print(resultDF)

           ID students  Rank
student1  S01     john     1
student2  S02      ram     2
student3  S03    shyam     3
student4  S04   shivam     4
student5  S05  shubham     5
student6  S06    rishi     6
           ID students  Rank  Roll No  Marks
student1  S01     john   1.0      NaN    NaN
student2  S02      ram   2.0      NaN    NaN
student3  S03    shyam   3.0      NaN    NaN
student4  S04   shivam   4.0      NaN    NaN
student5  S05  shubham   5.0      NaN    NaN
student6  S06    rishi   6.0      NaN    NaN
student1  NaN      NaN   NaN      1.0   98.0
student2  NaN      NaN   NaN      4.0   87.0
student3  NaN      NaN   NaN      7.0   77.0
student4  NaN      NaN   NaN      5.0   69.0
student5  NaN      NaN   NaN      7.0   90.0
student6  NaN      NaN   NaN      9.0   85.0

In [9]:
# series in pandas 

data = [10,20,30,40,50,60,70]

S = pd.Series(data)

S

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [10]:
# For access a value in index

data = [10,20,30,40,50,60,70]

S = pd.Series(data)
S[2]
S[4]

np.int64(50)

In [11]:
# combine two pandas 

data1 = [10,20,30,40,50,60,70]
data2 = [1,2,3,4,5,6,7]

S1 = pd.Series(data1)
S2 = pd.Series(data2)

S1
S2


def demo(data1, data2):
    if (data1 > data2):
        return data1
    else:
        return data2
    

Result = S1.combine(S2,demo)
print("\n after combine\n",Result)

 after combine
 0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [12]:
# append a catogorical series 

S = pd.Series(["s", "i", "r", "o", "h","i"], dtype="category")

S

S = S.cat.add_categories("ji")
S

0    s
1    i
2    r
3    o
4    h
5    i
dtype: category
Categories (6, str): ['h', 'i', 'o', 'r', 's', 'ji']

In [13]:
# remove a catagorical Series

S = pd.Series(["s", "i", "r", "o", "h","ji"], dtype="category")

S

S = S.cat.remove_categories("ji")
S

0      s
1      i
2      r
3      o
4      h
5    NaN
dtype: category
Categories (5, str): ['h', 'i', 'o', 'r', 's']

In [14]:
# Add New column using Insert(), assign(), end()

dataset = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
        'Rank'    :[1,2,3,4,5,6],
        'Marks'   :[98,87,77,69,90,85]
}

dataframe = pd.DataFrame(dataset)
dataframe

# adding new column

# use a valid integer location, a string column name, and a list of values matching the number of rows

dataframe.insert(loc=2, column='Roll No', value=[201,202,203,204,205,206])
dataframe

    ID students  Roll No  Rank  Marks
0  S01     john      201     1     98
1  S02      ram      202     2     87
2  S03    shyam      203     3     77
3  S04   shivam      204     4     69
4  S05  shubham      205     5     90
5  S06    rishi      206     6     85

In [15]:
dataset = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
        'Rank'    :[1,2,3,4,5,6],
        'Marks'   :[98,87,77,69,90,85],
        'Roll No' :[201,202,203,204,205,206]
}      


dataframe = pd.DataFrame(dataset)
dataframe

# dropping a Row/ column

ResultDF = dataframe.drop(labels=2, axis = (0))
ResultDF

    ID students  Rank  Marks  Roll No
0  S01     john     1     98      201
1  S02      ram     2     87      202
3  S04   shivam     4     69      204
4  S05  shubham     5     90      205
5  S06    rishi     6     85      206

In [16]:
# sort the dataframe 

dataset = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
        'Rank'    :[1,2,3,4,5,6],
        'Marks'   :[98,87,77,69,90,85],
        'Roll No' :[201,202,203,204,205,206]
}      


df = pd.DataFrame(dataset, index=['Row1','Row2','Row3','Row4','Row5','Row6'])
df

print(df.sort_values(by=['Rank'],ascending=False))

       ID students  Rank  Marks  Roll No
Row6  S06    rishi     6     85      206
Row5  S05  shubham     5     90      205
Row4  S04   shivam     4     69      204
Row3  S03    shyam     3     77      203
Row2  S02      ram     2     87      202
Row1  S01     john     1     98      201

In [17]:
# duplicates in pandas 

dataset = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
        'Rank'    :[1,2,3,4,5,6],
        'Marks'   :[98,87,77,69,90,85],
        'Roll No' :[201,202,203,204,205,206]
}      


df = pd.DataFrame(dataset)
df

result = df.duplicated()
result

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [18]:
# String  Operations on text data

dataset = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
        'Rank'    :[1,2,3,4,5,6],
        'Marks'   :[98,87,77,69,90,85],
        'Roll No' :[201,202,203,204,205,206]
}      


# create a series

S = pd.Series(dataset)
S

# convert the text to uppercase,lowercase,comelcase,length,count

print(S.str.lower())
print(S.str.upper())
print(S.str.title())
print(S.str.len())
print(S.str.count('john'))

ID         NaN
students   NaN
Rank       NaN
Marks      NaN
Roll No    NaN
dtype: float64
ID         NaN
students   NaN
Rank       NaN
Marks      NaN
Roll No    NaN
dtype: float64
ID         NaN
students   NaN
Rank       NaN
Marks      NaN
Roll No    NaN
dtype: float64
ID          6
students    6
Rank        6
Marks       6
Roll No     6
dtype: int64
ID         NaN
students   NaN
Rank       NaN
Marks      NaN
Roll No    NaN
dtype: float64

In [19]:
# Group the data 

dataset = { 
         'ID'       :["S01","S02","S03","S04","S05","S06"],
         'students': ["john", "ram", "shyam","shivam","shubham","rishi"],
        'Rank'    :[1,2,3,4,5,6],
        'Marks'   :[98,87,77,69,90,85],
        'Roll No' :[201,202,203,204,205,206]
}      

df = pd.DataFrame(dataset)
df

result = df.groupby('students')
result.first()

           ID  Rank  Marks  Roll No
students
john      S01     1     98      201
ram       S02     2     87      202
rishi     S06     6     85      206
shivam    S04     4     69      204
shubham   S05     5     90      205
shyam     S03     3     77      203

In [20]:
# statical function

marks = {
    'maths':[90,80,70,79,None, 70],
    'english':[78,88,98,93,None,55],
    'science':[70,80,90,None,75,86]

}

df = pd.DataFrame(marks)
df


df.sum()
df.count()
df.max()
df.min()
df.mean()
df.median()
df.std()
df.describe()

           maths    english    science
count   5.000000   5.000000   5.000000
mean   77.800000  82.400000  80.200000
std     8.318654  17.008821   8.074652
min    70.000000  55.000000  70.000000
25%    70.000000  78.000000  75.000000
50%    79.000000  88.000000  80.000000
75%    80.000000  93.000000  86.000000
max    90.000000  98.000000  90.000000

In [ ]:
import pandas as pd
import matplotlib as plt



data = {
    'temp': [45,54,34,44,53,46],
    'humidity': [30,34,24,22,43,45],
    'wind': [20,12,19,24,30,25],
    'precipitation':[17,25,28,33,44,32]
}

df = dataframe(data)

df.plot()
plt.show()